import type { KieModelEntry } from "../types";

export const IMAGE_MODELS: KieModelEntry[] = [
  {
    id: "gpt-image-2",
    displayName: "GPT Image 2",
    provider: "kie",
    category: "image",
    adapter: "market_task",
    endpoint: "/api/v1/jobs/createTask",
    providerModel: "gpt-image-2",
    capabilities: {
      imageGeneration: true,
      textToImage: true,
      imageToImage: true,
      referenceImages: true,
      aspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
      maxReferenceImages: 4,
    },
    quality: {
      levels: ["low", "medium", "high"],
      default: "medium",
      mapping: { low: "1K", medium: "2K", high: "4K" },
    },
    defaults: { isDefault: true },
    enabled: true,
    useCases: ["text-to-image", "image-to-image", "general purpose"],
  },
  {
    id: "nano-banana-2",
    displayName: "Nano Banana 2",
    provider: "kie",
    category: "image",
    adapter: "market_task",
    endpoint: "/api/v1/jobs/createTask",
    providerModel: "nano-banana-2",
    capabilities: {
      imageGeneration: true,
      textToImage: true,
      imageToImage: true,
      referenceImages: true,
      aspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
      maxReferenceImages: 8,
    },
    enabled: true,
    aliases: ["nano-banana-2-lite"],
    useCases: ["reference workflows", "image generation", "fast visual iterations"],
  },
  {
    id: "seedream-5-pro",
    displayName: "Seedream 5.0 Pro",
    provider: "kie",
    category: "image",
    adapter: "market_task",
    endpoint: "/api/v1/jobs/createTask",
    providerModel: "seedream-5-pro",
    capabilities: {
      imageGeneration: true,
      textToImage: true,
      imageToImage: true,
      referenceImages: true,
      aspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
      maxReferenceImages: 4,
    },
    quality: {
      levels: ["low", "medium", "high"],
      default: "medium",
      mapping: { low: "1K", medium: "2K", high: "4K" },
    },
    enabled: true,
    useCases: ["high-quality imagery", "photoreal/art", "reference workflows"],
  },
  {
    id: "wan-2-7-image-pro",
    displayName: "Wan 2.7 Image Pro",
    provider: "kie",
    category: "image",
    adapter: "market_task",
    endpoint: "/api/v1/jobs/createTask",
    providerModel: "wan-2-7-image-pro",
    capabilities: {
      imageGeneration: true,
      textToImage: true,
      imageToImage: true,
      imageEdit: true,
      referenceImages: true,
      multiReference: true,
      highResolution: true,
      aspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
      maxReferenceImages: 8,
    },
    quality: {
      levels: ["low", "medium", "high"],
      default: "medium",
      mapping: { low: "1K", medium: "2K", high: "4K" },
    },
    enabled: true,
    useCases: ["multi-reference", "image editing", "high-resolution", "complex compositions"],
  },
  {
    id: "ideogram-v3",
    displayName: "Ideogram V3",
    provider: "kie",
    category: "image",
    adapter: "market_task",
    endpoint: "/api/v1/jobs/createTask",
    providerModel: "ideogram-v3",
    capabilities: {
      imageGeneration: true,
      textToImage: true,
      typography: true,
      aspectRatios: ["1:1", "16:9", "9:16", "4:3", "3:4"],
    },
    enabled: true,
    useCases: ["posters", "advertising creatives", "typography-heavy imagery"],
  },
];
