import type { KieModelEntry } from "../types";

export const VIDEO_MODELS: KieModelEntry[] = [
  {
    id: "kling-3",
    displayName: "Kling 3",
    provider: "kie",
    category: "video",
    adapter: "market_task",
    endpoint: "/api/v1/jobs/createTask",
    providerModel: "kling-3",
    capabilities: {
      videoGeneration: true,
      textToVideo: true,
      imageToVideo: true,
      startFrame: true,
      endFrame: true,
      multiShot: true,
      elementReferences: true,
      referenceImages: true,
      sound: true,
      audio: true,
      aspectRatios: ["16:9", "9:16", "1:1"],
      durations: [5, 10, 15],
    },
    quality: {
      levels: ["low", "medium", "high"],
      default: "medium",
      mapping: { low: "std", medium: "pro", high: "4K" },
    },
    defaults: { isDefault: true },
    enabled: true,
  },
  {
    id: "veo-3-1",
    displayName: "Veo 3.1",
    provider: "kie",
    category: "video",
    adapter: "veo",
    endpoint: "/api/v1/veo/generate",
    providerModel: "veo-3-1",
    capabilities: {
      videoGeneration: true,
      textToVideo: true,
      imageToVideo: true,
      startFrame: true,
      endFrame: true,
      referenceImages: true,
      referenceVideo: true,
      aspectRatios: ["16:9", "9:16", "1:1"],
      resolutions: ["1080p", "4K"],
      durations: [5, 8, 10],
    },
    quality: {
      levels: ["low", "medium", "high"],
      default: "medium",
      mapping: { low: "lite", medium: "fast", high: "quality" },
    },
    enabled: true,
  },
  {
    id: "seedance-2-5",
    displayName: "Seedance 2.5",
    provider: "kie",
    category: "video",
    adapter: "market_task",
    endpoint: "/api/v1/jobs/createTask",
    providerModel: "seedance-2-5",
    capabilities: {
      videoGeneration: true,
      textToVideo: true,
      imageToVideo: true,
      referenceImages: true,
      aspectRatios: ["16:9", "9:16", "1:1"],
      durations: [5, 10, 15, 30],
    },
    enabled: true,
    aliases: ["bytedance-v1-lite-i2v"],
    useCases: ["multimodal", "longer-form generation"],
  },
  {
    id: "wan-2-7",
    displayName: "Wan 2.7",
    provider: "kie",
    category: "video",
    adapter: "market_task",
    endpoint: "/api/v1/jobs/createTask",
    providerModel: "wan-2-7",
    capabilities: {
      videoGeneration: true,
      textToVideo: true,
      imageToVideo: true,
      referenceToVideo: true,
      videoEdit: true,
      startFrame: true,
      referenceImages: true,
      aspectRatios: ["16:9", "9:16", "1:1"],
      durations: [5, 10],
    },
    enabled: true,
    useCases: ["text-to-video", "image-to-video", "reference-to-video", "video editing"],
  },
];
