-- Hardening PR2 — Live Research Trace.
-- A monotonic, service-owned trace ledger gives SSE a durable replay cursor and keeps
-- browser observability independent from the orchestration lease/poll cadence.

CREATE TABLE IF NOT EXISTS public.research_progress_events (
  sequence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  root_factory_job_id UUID NOT NULL REFERENCES public.factory_jobs(id) ON DELETE CASCADE,
  job_id UUID REFERENCES public.factory_jobs(id) ON DELETE CASCADE,
  research_run_id UUID REFERENCES public.research_runs(id) ON DELETE CASCADE,
  scout_role TEXT,
  event_type TEXT NOT NULL,
  dedupe_key TEXT NOT NULL UNIQUE,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT research_progress_events_event_type_nonempty CHECK (length(trim(event_type)) > 0),
  CONSTRAINT research_progress_events_scout_role_check CHECK (
    scout_role IS NULL OR scout_role IN (
      'market_competitor',
      'mechanics',
      'player_voice',
      'gameplay_visual',
      'white_space_contrarian'
    )
  )
);

CREATE INDEX IF NOT EXISTS idx_research_progress_root_sequence
  ON public.research_progress_events(root_factory_job_id, sequence_id);
CREATE INDEX IF NOT EXISTS idx_research_progress_run_sequence
  ON public.research_progress_events(research_run_id, sequence_id)
  WHERE research_run_id IS NOT NULL;

ALTER TABLE public.research_progress_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.research_progress_events FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.research_progress_events TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

CREATE OR REPLACE FUNCTION public.research_record_progress_event(payload JSONB)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_root_job_id UUID;
  v_job_id UUID;
  v_research_run_id UUID;
  v_scout_role TEXT := NULLIF(payload->>'scout_role', '');
  v_event_type TEXT := NULLIF(trim(payload->>'event_type'), '');
  v_dedupe_key TEXT := NULLIF(trim(payload->>'dedupe_key'), '');
  v_payload JSONB := COALESCE(payload->'payload', '{}'::jsonb);
  v_row public.research_progress_events%ROWTYPE;
BEGIN
  SELECT fj.id
  INTO v_root_job_id
  FROM public.factory_jobs AS fj
  WHERE fj.id::TEXT = payload->>'root_factory_job_id'
    AND fj.workflow_kind = 'game_discovery_batch'
    AND fj.workflow_version = 2;

  IF v_root_job_id IS NULL THEN
    RAISE EXCEPTION 'invalid Game Discovery v2 root job';
  END IF;
  IF v_event_type IS NULL OR v_event_type !~ '^(research|concept|job)\.' THEN
    RAISE EXCEPTION 'invalid research progress event type';
  END IF;
  IF v_dedupe_key IS NULL OR length(v_dedupe_key) > 500 THEN
    RAISE EXCEPTION 'invalid research progress dedupe key';
  END IF;

  SELECT fj.id INTO v_job_id
  FROM public.factory_jobs AS fj
  WHERE fj.id::TEXT = NULLIF(payload->>'job_id', '');

  SELECT rr.id INTO v_research_run_id
  FROM public.research_runs AS rr
  WHERE rr.id::TEXT = NULLIF(payload->>'research_run_id', '');

  INSERT INTO public.research_progress_events(
    root_factory_job_id,
    job_id,
    research_run_id,
    scout_role,
    event_type,
    dedupe_key,
    payload
  )
  VALUES (
    v_root_job_id,
    v_job_id,
    v_research_run_id,
    v_scout_role,
    v_event_type,
    v_dedupe_key,
    v_payload
  )
  ON CONFLICT (dedupe_key) DO UPDATE
    SET dedupe_key = EXCLUDED.dedupe_key
  RETURNING * INTO v_row;

  RETURN jsonb_build_object(
    'sequence_id', v_row.sequence_id,
    'event_type', v_row.event_type,
    'created_at', v_row.created_at,
    'duplicate', v_row.created_at < NOW() - INTERVAL '1 millisecond'
  );
END;
$$;

REVOKE ALL ON FUNCTION public.research_record_progress_event(JSONB)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.research_record_progress_event(JSONB)
  TO service_role;

-- Existing workflow events remain the orchestration source of truth. Mirror only the
-- research/concept lifecycle (plus a user cancellation) into the monotonic trace ledger.
CREATE OR REPLACE FUNCTION public.research_progress_mirror_factory_event()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_root_job_id UUID;
  v_root_kind TEXT;
  v_root_version INTEGER;
  v_research_run_id UUID;
  v_scout_role TEXT;
BEGIN
  SELECT COALESCE(root.id, child.id), COALESCE(root.workflow_kind, child.workflow_kind), COALESCE(root.workflow_version, child.workflow_version)
  INTO v_root_job_id, v_root_kind, v_root_version
  FROM public.factory_jobs AS child
  LEFT JOIN public.factory_jobs AS root
    ON root.id::TEXT = child.input->>'root_factory_job_id'
  WHERE child.id = NEW.job_id;

  IF v_root_job_id IS NULL OR v_root_kind <> 'game_discovery_batch' OR v_root_version <> 2 THEN
    RETURN NEW;
  END IF;

  SELECT rr.id INTO v_research_run_id
  FROM public.research_runs AS rr
  WHERE rr.id::TEXT = NULLIF(NEW.payload->>'research_run_id', '')
  LIMIT 1;
  v_scout_role := NULLIF(NEW.payload->>'scout_role', '');

  INSERT INTO public.research_progress_events(
    root_factory_job_id,
    job_id,
    research_run_id,
    scout_role,
    event_type,
    dedupe_key,
    payload,
    created_at
  )
  VALUES (
    v_root_job_id,
    NEW.job_id,
    v_research_run_id,
    CASE
      WHEN v_scout_role IN ('market_competitor','mechanics','player_voice','gameplay_visual','white_space_contrarian')
        THEN v_scout_role
      ELSE NULL
    END,
    NEW.event_type,
    'workflow:' || NEW.id::TEXT,
    NEW.payload || jsonb_build_object('workflow_event_id', NEW.id),
    NEW.created_at
  )
  ON CONFLICT (dedupe_key) DO NOTHING;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_research_progress_mirror_factory_event ON public.factory_workflow_events;
CREATE TRIGGER trg_research_progress_mirror_factory_event
AFTER INSERT ON public.factory_workflow_events
FOR EACH ROW
WHEN (
  NEW.event_type LIKE 'research.%'
  OR NEW.event_type LIKE 'concept.%'
  OR NEW.event_type = 'job.cancelled'
)
EXECUTE FUNCTION public.research_progress_mirror_factory_event();

COMMENT ON TABLE public.research_progress_events IS
  'Durable monotonic Game Discovery v2 research trace used for authenticated SSE replay; not Stage 6 memory.';
