import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const migration = readFileSync(
  join(process.cwd(), "supabase/migrations/20260821090000_live_research_trace.sql"),
  "utf8",
);
const sseRoute = readFileSync(
  join(process.cwd(), "app/api/discovery/batches/[runId]/trace/route.ts"),
  "utf8",
);
const taskCard = readFileSync(
  join(process.cwd(), "components/chat/discovery-v2-task-card.tsx"),
  "utf8",
);
const composer = readFileSync(
  join(process.cwd(), "components/chat/chat-composer.tsx"),
  "utf8",
);
const traceUi = readFileSync(
  join(process.cwd(), "components/chat/research-live-trace.tsx"),
  "utf8",
);
const scout = readFileSync(
  join(process.cwd(), "lib/research-intelligence/kie-research-scout.ts"),
  "utf8",
);
const internalScoutRoute = readFileSync(
  join(process.cwd(), "app/api/internal/research-scout-execute/route.ts"),
  "utf8",
);

describe("PR2 durable research progress ledger", () => {
  it("uses a monotonic durable sequence for lossless SSE replay", () => {
    expect(migration).toContain("CREATE TABLE IF NOT EXISTS public.research_progress_events");
    expect(migration).toContain("sequence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
    expect(migration).toContain("idx_research_progress_root_sequence");
    expect(migration).toContain("dedupe_key TEXT NOT NULL UNIQUE");
    expect(migration).toContain("research_record_progress_event");
  });

  it("remains service-owned and does not expose the trace table to browser roles", () => {
    expect(migration).toContain("ALTER TABLE public.research_progress_events ENABLE ROW LEVEL SECURITY");
    expect(migration).toContain("REVOKE ALL ON TABLE public.research_progress_events FROM PUBLIC, anon, authenticated");
    expect(migration).toMatch(/REVOKE ALL ON FUNCTION public\.research_record_progress_event\(JSONB\)[\s\S]*FROM PUBLIC, anon, authenticated/);
    expect(migration).not.toContain("GRANT USAGE, SELECT ON ALL SEQUENCES");
  });

  it("mirrors durable Research/Concept workflow transitions into the same trace", () => {
    expect(migration).toContain("research_progress_mirror_factory_event");
    expect(migration).toContain("NEW.event_type LIKE 'research.%'");
    expect(migration).toContain("NEW.event_type LIKE 'concept.%'");
    expect(migration).toContain("NEW.event_type = 'job.cancelled'");
  });
});

describe("PR2 authenticated SSE replay contract", () => {
  it("uses Last-Event-ID and the monotonic cursor instead of browser polling", () => {
    expect(sseRoute).toContain('request.headers.get("last-event-id")');
    expect(sseRoute).toContain('.gt("sequence_id", cursor)');
    expect(sseRoute).toContain('"Content-Type": "text/event-stream; charset=utf-8"');
    expect(sseRoute).toContain('"X-Accel-Buffering": "no"');
    expect(sseRoute).toContain('event: "trace"');
  });

  it("authenticates and authorizes the run before opening the stream", () => {
    expect(sseRoute).toContain("getSessionUser");
    expect(sseRoute).toContain("getGameDiscoveryBatch");
    expect(sseRoute).toContain("if (!user)");
    expect(sseRoute).toContain("root.factory_job_id");
  });
});

describe("PR2 live research UI", () => {
  it("removes the old 5-second four-request polling loop", () => {
    expect(taskCard).not.toContain("const POLL_MS = 5_000");
    expect(taskCard).not.toMatch(/setInterval\(\(\) => void load\(\)/);
    expect(taskCard).toContain("<ResearchLiveTrace");
    expect(traceUi).toContain("new EventSource");
  });

  it("also removes the temporary PR1 composer polling detector", () => {
    expect(composer).not.toMatch(/setInterval\(\(\) => void inspect/);
    expect(composer).toContain("new EventSource");
    expect(composer).toContain("game-discovery-v2-activity");
  });

  it("surfaces Scouts, search, sources, evidence, elapsed and last activity", () => {
    expect(traceUi).toContain("Live Research Trace");
    expect(traceUi).toContain("elapsed");
    expect(traceUi).toContain("last activity");
    expect(traceUi).toContain("research.search.started");
    expect(traceUi).toContain("research.source.accepted");
    expect(traceUi).toContain("research.evidence.persisted");
    expect(traceUi).toContain("Live sources");
    expect(traceUi).toContain("Live evidence");
  });
});

describe("PR2 granular Scout progress", () => {
  it("emits search, safe-fetch, source and evidence lifecycle events", () => {
    for (const eventType of [
      "research.scout.started",
      "research.search.started",
      "research.search.completed",
      "research.source.fetch_started",
      "research.source.accepted",
      "research.source.rejected",
      "research.evidence.extracted",
      "research.scout.execution_completed",
    ]) {
      expect(scout).toContain(eventType);
    }
  });

  it("fails closed before the paid call if the initial durable trace cannot be written", () => {
    expect(internalScoutRoute).toContain("beforePaidCall");
    expect(internalScoutRoute).toContain('event.eventType === "research.search.started"');
    expect(internalScoutRoute).toContain("RESEARCH_PROGRESS_PERSIST_FAILED");
  });
});
